# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yannbourdeau/src/litesql-src-0.3.18

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yannbourdeau/src/litesql-src-0.3.18

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"devel\" \"examples\" \"generator\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.20.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.20.2/bin/cpack --config ./CPackSourceConfig.cmake /Users/yannbourdeau/src/litesql-src-0.3.18/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.20.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yannbourdeau/src/litesql-src-0.3.18/CMakeFiles /Users/yannbourdeau/src/litesql-src-0.3.18//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yannbourdeau/src/litesql-src-0.3.18/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named litesql

# Build rule for target.
litesql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 litesql
.PHONY : litesql

# fast build rule for target.
litesql/fast:
	$(MAKE) $(MAKESILENT) -f src/library/CMakeFiles/litesql.dir/build.make src/library/CMakeFiles/litesql.dir/build
.PHONY : litesql/fast

#=============================================================================
# Target rules for targets named litesql_backend_sqlite3

# Build rule for target.
litesql_backend_sqlite3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 litesql_backend_sqlite3
.PHONY : litesql_backend_sqlite3

# fast build rule for target.
litesql_backend_sqlite3/fast:
	$(MAKE) $(MAKESILENT) -f src/library/CMakeFiles/litesql_backend_sqlite3.dir/build.make src/library/CMakeFiles/litesql_backend_sqlite3.dir/build
.PHONY : litesql_backend_sqlite3/fast

#=============================================================================
# Target rules for targets named litesql-util

# Build rule for target.
litesql-util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 litesql-util
.PHONY : litesql-util

# fast build rule for target.
litesql-util/fast:
	$(MAKE) $(MAKESILENT) -f src/library/CMakeFiles/litesql-util.dir/build.make src/library/CMakeFiles/litesql-util.dir/build
.PHONY : litesql-util/fast

#=============================================================================
# Target rules for targets named litesql_sqlite

# Build rule for target.
litesql_sqlite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 litesql_sqlite
.PHONY : litesql_sqlite

# fast build rule for target.
litesql_sqlite/fast:
	$(MAKE) $(MAKESILENT) -f src/library/CMakeFiles/litesql_sqlite.dir/build.make src/library/CMakeFiles/litesql_sqlite.dir/build
.PHONY : litesql_sqlite/fast

#=============================================================================
# Target rules for targets named ddl2litesql

# Build rule for target.
ddl2litesql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ddl2litesql
.PHONY : ddl2litesql

# fast build rule for target.
ddl2litesql/fast:
	$(MAKE) $(MAKESILENT) -f src/generator/CMakeFiles/ddl2litesql.dir/build.make src/generator/CMakeFiles/ddl2litesql.dir/build
.PHONY : ddl2litesql/fast

#=============================================================================
# Target rules for targets named litesql-gen

# Build rule for target.
litesql-gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 litesql-gen
.PHONY : litesql-gen

# fast build rule for target.
litesql-gen/fast:
	$(MAKE) $(MAKESILENT) -f src/generator/CMakeFiles/litesql-gen.dir/build.make src/generator/CMakeFiles/litesql-gen.dir/build
.PHONY : litesql-gen/fast

#=============================================================================
# Target rules for targets named model

# Build rule for target.
model: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model
.PHONY : model

# fast build rule for target.
model/fast:
	$(MAKE) $(MAKESILENT) -f src/generator/CMakeFiles/model.dir/build.make src/generator/CMakeFiles/model.dir/build
.PHONY : model/fast

#=============================================================================
# Target rules for targets named test-backend-loading

# Build rule for target.
test-backend-loading: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-backend-loading
.PHONY : test-backend-loading

# fast build rule for target.
test-backend-loading/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/test-backend-loading.dir/build.make src/tests/CMakeFiles/test-backend-loading.dir/build
.PHONY : test-backend-loading/fast

#=============================================================================
# Target rules for targets named test-update-table

# Build rule for target.
test-update-table: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-update-table
.PHONY : test-update-table

# fast build rule for target.
test-update-table/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/test-update-table.dir/build.make src/tests/CMakeFiles/test-update-table.dir/build
.PHONY : test-update-table/fast

#=============================================================================
# Target rules for targets named test-datetime

# Build rule for target.
test-datetime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-datetime
.PHONY : test-datetime

# fast build rule for target.
test-datetime/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/test-datetime.dir/build.make src/tests/CMakeFiles/test-datetime.dir/build
.PHONY : test-datetime/fast

#=============================================================================
# Target rules for targets named test-split

# Build rule for target.
test-split: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-split
.PHONY : test-split

# fast build rule for target.
test-split/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/test-split.dir/build.make src/tests/CMakeFiles/test-split.dir/build
.PHONY : test-split/fast

#=============================================================================
# Target rules for targets named test-selectquery

# Build rule for target.
test-selectquery: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-selectquery
.PHONY : test-selectquery

# fast build rule for target.
test-selectquery/fast:
	$(MAKE) $(MAKESILENT) -f src/tests/CMakeFiles/test-selectquery.dir/build.make src/tests/CMakeFiles/test-selectquery.dir/build
.PHONY : test-selectquery/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/example.dir/build.make src/examples/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named graph

# Build rule for target.
graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph
.PHONY : graph

# fast build rule for target.
graph/fast:
	$(MAKE) $(MAKESILENT) -f src/examples/CMakeFiles/graph.dir/build.make src/examples/CMakeFiles/graph.dir/build
.PHONY : graph/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... dist"
	@echo "... ddl2litesql"
	@echo "... example"
	@echo "... graph"
	@echo "... litesql"
	@echo "... litesql-gen"
	@echo "... litesql-util"
	@echo "... litesql_backend_sqlite3"
	@echo "... litesql_sqlite"
	@echo "... model"
	@echo "... test-backend-loading"
	@echo "... test-datetime"
	@echo "... test-selectquery"
	@echo "... test-split"
	@echo "... test-update-table"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

